# Generated by Django 4.2.5 on 2023-09-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptis', '0002_alter_rol_borrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='codigo',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='rango',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='correo_elec',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='identificador',
            field=models.IntegerField(unique=True),
        ),
    ]
