# Generated by Django 4.2.5 on 2023-09-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptis', '0003_semester_activo_alter_course_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='run',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
