# Generated by Django 4.2.5 on 2023-09-25 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ptis', '0004_alter_user_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPtis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_materno', models.CharField(max_length=254)),
                ('run', models.CharField(max_length=12, null=True)),
                ('borrado', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ptis.rol')),
            ],
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ptis.userptis'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ptis.userptis'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ptis.userptis'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
